version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tapsilat"
    assignees:
      - "tapsilat"
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tapsilat"
    assignees:
      - "tapsilat"
    commit-message:
      prefix: "ci"
      include: "scope" 